language: python
python:
  - "2.7"
addons:
    apt:
        packages:
        - python-pygame
install:
    - pip install -r .travis_requirements.txt
script: 
    - python main.py
virtualenv:
    system_site_packages: true